//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3D_renderer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3D_renderer.Resource2", typeof(Resource2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        /// 
        /// 
        /// 
        /// 
        /// 
        /// 
        ///.
        ///&apos;
        ///&apos;
        ///&apos;
        ///&apos;
        ///-
        ///-
        ///-
        ///-
        ///,
        ///,
        ///,
        ///,
        ///:
        ///:
        ///:
        ///:
        ///_
        ///_
        ///_
        ///_
        ///&quot;
        ///&quot;
        ///&quot;
        ///&quot;
        ///;
        ///;
        ///;
        ///;
        ///&lt;
        ///&lt;
        ///&lt;
        ///&lt;
        ///&gt;
        ///&gt;
        ///&gt;
        ///&gt;
        ////
        ////
        ////
        ////
        ///\
        ///\
        ///\
        ///\
        ///!
        ///!
        ///!
        ///!
        ///+
        ///+
        ///+
        ///+
        ///*
        ///*
        ///*
        ///*
        ///=
        ///=
        ///=
        ///=
        ///^
        ///^
        ///^
        ///^
        ///L
        ///L
        ///L
        ///L
        ///J
        ///J
        ///J
        ///J
        ///?
        ///?
        ///?
        ///?
        ///T
        ///T
        ///T
        ///T
        ///Y
        ///Y
        ///Y
        ///Y
        ///(
        ///(
        ///(
        ///(
        ///)
        ///)
        ///)
        ///)
        ///7
        ///7
        ///7
        ///7
        ///C
        ///C
        ///C
        ///C
        ///F
        ///F
        ///F
        ///F
        ///2
        ///2
        ///2
        ///2
        ///1
        ///1
        ///1
        ///1
        ///I
        ///I
        ///I
        ///I
        ///3
        ///3
        ///3
        ///3
        ///5
        ///5
        ///5
        ///5
        ///Z
        ///Z
        ///Z
        ///Z
        ///[
        ///[
        ///[
        ///[
        ///]
        ///]
        ///]
        ///]
        ///S
        ///S
        ///S
        ///S
        ///V
        ///V
        ///V
        ///V
        ///E
        ///E
        ///E
        ///E
        ///A
        ///A
        ///A
        ///A
        ///X
        ///X
        ///X
        ///X
        ///P
        ///P
        ///P
        ///P
        ///G
        ///G
        ///G        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string levels {
            get {
                return ResourceManager.GetString("levels", resourceCulture);
            }
        }
    }
}
